# Generated by Django 3.1.7 on 2021-04-12 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0007_auto_20210407_1935'),
        ('polls_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user_service.userprofile'),
            preserve_default=False,
        ),
    ]
