# Generated by Django 3.1.7 on 2021-04-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_auto_20210404_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='Age'),
        ),
    ]
