# Generated by Django 3.1.7 on 2021-04-07 19:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0006_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/no_photo_icon.png', storage=django.core.files.storage.FileSystemStorage(location='/app/media/'), upload_to='avatars'),
        ),
    ]
