# Generated by Django 3.1.7 on 2021-04-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='test', max_length=255, verbose_name='Chat name'),
            preserve_default=False,
        ),
    ]
