# Generated by Django 3.1.7 on 2021-04-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0007_auto_20210407_1935'),
        ('chat_service', '0002_chat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(to='user_service.UserProfile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_service.userprofile'),
        ),
    ]
