# Generated by Django 3.1.7 on 2021-04-08 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0007_auto_20210407_1935'),
        ('chat_service', '0003_auto_20210407_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_service.userprofile'),
        ),
    ]
